let g:vim_home = fnamemodify(resolve(expand('<sfile>:p')), ':h')
let &runtimepath .= ',' .g:vim_home 

exec 'source ' . g:vim_home . '/src/preplugin.vim'
exec 'source ' . g:vim_home . '/src/plugins.vim'
exec 'source ' . g:vim_home . '/src/coc_config.vim'
exec 'source ' . g:vim_home . '/src/postplugin.vim'
exec 'source ' . g:vim_home . '/src/syntax.vim'
exec 'source ' . g:vim_home . '/src/treesitter_settup.vim'

language en_US.UTF-8
